apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  containers:
    - name: hello-world
      image: hello-world:1.0.0
      ports:
        - containerPort: 8080